spring.application.name=usuarios-servicio
server.port=8082

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:usuariosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Para que ejecute data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
