# Puerto dinámico para Render
server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/buyhistory_users
spring.data.mongodb.database=buyhistory_users

logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

# Spring Security: nada especial, solo logs suaves
logging.level.org.springframework.security=INFO
